### ISSUE TITLE
Minor Changes in UI

### ISSUE THREAD

**Issue by wweverma1** [tsg-iitkgp/tsg-site#64]
While surfing the **TSG website** I observed some issues in **Facilities and Events** section which needed to be fixed.

- First of all there wasn't any **close button** for Modal which is important as people wont know how to close a modal once it is opened, especially in mobile devices.
- Secondly I observed that on Modal with scrollbar once I reach the end of Modal the body starts to scroll. 
I'm attaching its video below:

https://user-images.githubusercontent.com/51537596/135874084-b19e326d-a420-4c09-a649-407e543300da.mp4

**Comment by wweverma1** [comment]
@sahil-shubham I've worked on this and raised a PR to fix these issues.
PR: https://github.com/tsg-iitkgp/tsg-site/pull/65
Kindly review & fix them.
Also please add **hacktoberfest-accepted** label to it.

**Comment by sahil-shubham** [comment]
Thanks for the issue and pull request @wweverma1 I don't work on this project anymore. 

@Praneeth-rdy can you take a look into his pull request and also decide whether this repository should be part of hacktoberfest or not.
